### ISSUE TITLE
[FEAT] 홈 화면 구현

### ISSUE THREAD

**Issue by dodengdeng** [WebOS-TEAM-DEVMONSTER/FarmOSApplication#1]
## 🌴 작업 브랜치 

sojung

## 💼 TASK 개요 

farm os 농장 관리 어플리케이션의 홈 화면을 구현합니다.

## ✅ TODO 및 진행현황 

- [ ] 홈 화면 퍼블리싱
- [ ] 홈 화면을 들어간 직후 농장 정보, 주인 정보 불러오기
- [ ] 추가 버튼 클릭 시 
- [ ] 삭제 버튼 클릭 시
