### ISSUE TITLE
[FEAT] 홈 화면 변경 스마트팜 상태관리 화면 구현

### ISSUE THREAD

**Issue by dodengdeng** [WebOS-TEAM-DEVMONSTER/FarmOSApplication#13]
## 🌴 작업 브랜치 
sojeong

## 💼 TASK 개요 
홈 화면 디자인 변경, 스마트팜 상태관리(온습도 화면) 구현하기, 서버 pull해서 로컬로 연결 테스트해보기

## ✅ TODO 및 진행현황 

- [x] 메인 홈 화면 만들기
- [x] 스마트팜 홈 화면 변경하기
- [x] 스마트팜 상태관리 화면 구현하기
- [x] 로컬 서버 연결 테스트 해보기
